name: Kompy

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    - cron: '0 1 * * 1'


permissions:
  contents: read

jobs:
  build:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
          cache: 'pip'
      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 10
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest rich pytest-pretty sphinx coverage
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          sudo apt update
      - name: Lint with flake8
        run: |
          flake8 . --count --max-complexity=25 --max-line-length=120 --statistics
      - name: Test with pytest
        run: |
          pytest .
        env:
          KOMOOT_EMAIL: ${{ secrets.KOMOOT_EMAIL }}
          KOMOOT_PASSWORD: ${{ secrets.KOMOOT_PASSWORD }}
          KOMOOT_VALID_TOUR_ID: ${{ secrets.KOMOOT_VALID_TOUR_ID }}
      - name: Run Coverage with coverage.py
        run: |
          coverage run -m pytest
          coverage report -m
        env:
          KOMOOT_EMAIL: ${{ secrets.KOMOOT_EMAIL }}
          KOMOOT_PASSWORD: ${{ secrets.KOMOOT_PASSWORD }}
          KOMOOT_VALID_TOUR_ID: ${{ secrets.KOMOOT_VALID_TOUR_ID }}
      - name: Coverage Badge
        uses: tj-actions/coverage-badge-py@v2

      - name: Verify Changed files
        uses: tj-actions/verify-changed-files@v16
        id: verify-changed-files
        with:
          files: coverage.svg

      - name: Commit files
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add coverage.svg
          git commit -m "Updated coverage.svg"

      - name: Push changes
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.github_token }}
          branch: ${{ github.ref }}
