name: Kompy

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    - cron: '0 1 * * 1'


permissions:
  contents: write

jobs:
  build:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install flake8 coverage
          sudo apt update
      - name: Lint with flake8
        run: |
          flake8 . --count --max-complexity=25 --max-line-length=120 --statistics
      - name: Run Tests
        run: |
          python -m unittest
        env:
          KOMOOT_EMAIL: ${{ secrets.KOMOOT_EMAIL }}
          KOMOOT_PASSWORD: ${{ secrets.KOMOOT_PASSWORD }}
          KOMOOT_VALID_TOUR_ID: ${{ secrets.KOMOOT_VALID_TOUR_ID }}
      - name: Run Coverage with coverage.py
        run: |
          coverage run -m unittest
          coverage report -m
        env:
          KOMOOT_EMAIL: ${{ secrets.KOMOOT_EMAIL }}
          KOMOOT_PASSWORD: ${{ secrets.KOMOOT_PASSWORD }}
          KOMOOT_VALID_TOUR_ID: ${{ secrets.KOMOOT_VALID_TOUR_ID }}